# Generated by Django 4.0.4 on 2022-04-27 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Название группы')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Группы студентов',
                'verbose_name_plural': 'Группа студентов',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Иван Иванов', max_length=1000, verbose_name='Фамилия Имя')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexing.group', verbose_name='Группа')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Студента',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='List_Of_Control_Activities_Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_point', models.IntegerField(verbose_name='Контрольная точка')),
                ('grade_service', models.CharField(max_length=350, verbose_name='Оценочное средство')),
                ('form_holding', models.CharField(max_length=350, verbose_name='Форма проведения')),
                ('order_holding', models.CharField(max_length=350, verbose_name='Порядок проведения')),
                ('evaluation_scale', models.CharField(max_length=350, verbose_name='Шкала оценивания')),
                ('evaluation_criteria', models.TextField(verbose_name='Критерии оценивания')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
            options={
                'verbose_name': ' Лист контрольных мероприятий содержание',
                'verbose_name_plural': ' Лист контрольных мероприятий содержание',
            },
        ),
        migrations.CreateModel(
            name='List_Of_Control_Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=350, verbose_name='Кафедра')),
                ('discipline', models.CharField(max_length=350, verbose_name='Дисциплина')),
                ('course', models.IntegerField(verbose_name='Курс')),
                ('semester', models.IntegerField(verbose_name='Семестр')),
                ('check_point_date_start', models.DateField(verbose_name='Контрольная точка #1')),
                ('check_point_date_end', models.DateField(verbose_name='Контрольная точка #2')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexing.group', verbose_name='Группа')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexing.list_of_control_activities_value', verbose_name='Содержание листа')),
            ],
            options={
                'verbose_name': ' Лист контрольных мероприятий',
                'verbose_name_plural': ' Лист контрольных мероприятий',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Лекция', max_length=1000, verbose_name='Тема занятия')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('time', models.IntegerField(default=45, verbose_name='Длительность занятия')),
                ('group', models.ManyToManyField(help_text='Это список доступных групп, выберите у какой группы будет занятие', to='indexing.group', verbose_name='Группа студентов')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятий',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grades', models.IntegerField(default=0, verbose_name='Оценка')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexing.lecture', verbose_name='За занятие')),
                ('key_to_student', models.ManyToManyField(to='indexing.students', verbose_name='Студентам')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Бал',
                'verbose_name_plural': 'Баллы',
            },
        ),
    ]
