# Generated by Django 4.0.4 on 2022-05-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexing', '0002_remove_list_of_control_activities_value_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'Оценка', 'verbose_name_plural': 'Оценки'},
        ),
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.CharField(help_text='Теория большого взрыва', max_length=1000, verbose_name='Тема занятия'),
        ),
        migrations.AlterField(
            model_name='students',
            name='full_name',
            field=models.CharField(help_text='Савельев Максим', max_length=1000, verbose_name='Фамилия Имя'),
        ),
    ]
