# Generated by Django 4.0.5 on 2022-06-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexing', '0006_alter_formholding_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradeitem',
            options={'verbose_name': 'Занятие (оценочное средство)', 'verbose_name_plural': 'Занятия (оценочное средства)'},
        ),
        migrations.AddField(
            model_name='graderesult',
            name='value',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='оценка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gradeserviceset',
            name='evaluation_rate',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Баллов за единицу'),
        ),
    ]
