# Generated by Django 4.0.5 on 2022-06-05 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexing', '0007_alter_gradeitem_options_graderesult_value_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradeitem',
            options={'ordering': ['grade_service_set', 'date'], 'verbose_name': 'Занятие (оценочное средство)', 'verbose_name_plural': 'Занятия (оценочное средства)'},
        ),
    ]
