# Generated by Django 4.0.5 on 2022-06-06 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexing', '0008_alter_gradeitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graderesult',
            options={'verbose_name': 'Результат (оценка)', 'verbose_name_plural': 'Результаты (оценки)'},
        ),
        migrations.AlterUniqueTogether(
            name='graderesult',
            unique_together={('grade_item', 'student')},
        ),
    ]
