# Generated by Django 4.0.5 on 2022-06-06 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indexing', '0010_rename_value_graderesult_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='teacher',
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Учитель'),
        ),
    ]
