# Generated by Django 4.0.5 on 2022-06-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexing', '0011_remove_group_teacher_group_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=1000, unique=True, verbose_name='Название группы'),
        ),
    ]
