# Generated by Django 4.0.4 on 2022-06-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexing', '0015_list_of_control_activities_evaluation_criteria_pa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_of_control_activities',
            name='name_pa',
            field=models.CharField(default='', max_length=350, verbose_name='Вид ПА'),
            preserve_default=False,
        ),
    ]
