# Generated by Django 4.0.4 on 2022-06-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexing', '0018_alter_list_of_control_activities_name_pa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_of_control_activities',
            name='faculty',
            field=models.CharField(choices=[('МиП', 'МиП'), ('ТД', 'ТД'), ('КТиИБ', 'КТиИБ'), ('УЭФ', 'УЭФ'), ('ЭиФ', 'ЭиФ'), ('ЛиЖ', 'ЛиЖ'), ('ЮФ', 'ЮФ')], default='КТиИБ', max_length=20, verbose_name='факультет'),
        ),
        migrations.AlterField(
            model_name='list_of_control_activities',
            name='name_pa',
            field=models.CharField(choices=[('Экзамен', 'Экзамен'), ('Зачёт', 'Зачёт')], default='Экзамен', max_length=20, verbose_name='Вид ПА'),
        ),
    ]
